modLoader="javafml"
loaderVersion="[30,)"
license="GPLv3"
issueTrackerURL="https://github.com/Autovw/BurgerMod/issues"

[[mods]] #mandatory
modId="burgermod"
version="1.2.0"
displayName="Burger Mod"
#updateJSONURL="http://myurl.me/"
displayURL="https://github.com/Autovw/BurgerMod"
logoFile="burgermod.png"
#credits="Thanks for this example mod goes to Java"
authors="Autovw"
description='''
A mod that adds in burgers along with scrambled eggs.
'''
itemIcon="burgermod:burger"
configBackground="minecraft:textures/block/bricks.png"

[[dependencies.burgermod]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.burgermod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1,1.16]"
    ordering="NONE"
    side="BOTH"
