modLoader="javafml"
loaderVersion="[31,)"
license="GPLv3"
issueTrackerURL="https://github.com/Autovw/BurgerMod/issues"

[[mods]] #mandatory
modId="burgermod"
version="1.7.0"
displayName="Burger Mod"
updateJSONURL="https://raw.githubusercontent.com/Autovw/ModUpdates/master/burgermod/update.json"
displayURL="https://github.com/Autovw/BurgerMod/wiki"
logoFile="burgermod.png"
#credits=""
authors="Autovw"
description='''
A mod that adds in burgers and other types of food that extend the vanilla game!

Visit the Burger Mod Wiki on GitHub, where you can find everything you need to know about the Burger Mod!
'''

[[dependencies.burgermod]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.burgermod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,1.16]"
    ordering="NONE"
    side="BOTH"

[modproperties.burgermod]
    configuredBackground="minecraft:textures/block/bricks.png" #Optional support for Configured mod.
    #As of version 1.2.0 Catalogue also supports images. Use "catalogueImageIcon" instead.
    catalogueItemIcon="burgermod:burger" #Optional support for Cataloque mod.
