modLoader="javafml"
loaderVersion="[34,)"
license="GPLv3"
issueTrackerURL="https://github.com/Autovw/BurgerMod/issues"

[[mods]] #mandatory
modId="burgermod"
version="1.4.1"
displayName="Burger Mod"
#updateJSONURL="http://myurl.me/"
displayURL="https://github.com/Autovw/BurgerMod/wiki"
logoFile="burgermod.png"
#credits=""
authors="Autovw"
description='''
A mod that adds in burgers along with scrambled eggs.

Visit the Burger Mod Wiki on GitHub, here you can find everything you need to know about the Burger Mod!
'''
itemIcon="burgermod:burger" #Optional support for Cataloque mod.
configBackground="minecraft:textures/block/bricks.png" #Optional support for Configured mod.

[[dependencies.burgermod]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.burgermod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17]"
    ordering="NONE"
    side="BOTH"
