modLoader="javafml"
loaderVersion="[2,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/Autovw/BurgerMod/issues"

[[mods]]
modId="burgermod"
version="${mod_version}"
displayName="Burger Mod"
updateJSONURL="https://raw.githubusercontent.com/Autovw/ModUpdates/master/burgermod/update.json"
displayURL="https://github.com/Autovw/BurgerMod/wiki"
logoFile="burgermod_banner.png"
#credits=""
authors="Autovw"
description='''
A fun little mod that adds in burgers and other types of food to extend the vanilla food experience!

Visit the Burger Mod Wiki on GitHub, where you can find everything you need to know about the Burger Mod!
'''

[[dependencies.burgermod]]
    modId="neoforge"
    type="required"
    versionRange="[21.7.1-beta,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.burgermod]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.7]"
    ordering="NONE"
    side="BOTH"

[modproperties.burgermod]
    catalogueItemIcon="burgermod:beef_burger" #Optional support for Cataloque mod.
    configuredBackground="minecraft:textures/block/bricks.png" #Optional support for Configured mod.
